name: Comprehensive Token Verification

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ultimate Token Verification
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      run: |
        # 다중 검증 로직
        if [ -z "$NOTION_TOKEN" ]; then
          echo "::error::Token is not set"
          exit 1
        fi

        # 접두사 확인
        if [[ ! "$NOTION_TOKEN" == rtn_* ]]; then
          echo "::error::Token must start with 'rtn_'"
          exit 1
        fi

        # 토큰 길이 검증
        TOKEN_LENGTH=${#NOTION_TOKEN}
        if [ $TOKEN_LENGTH -lt 40 ] || [ $TOKEN_LENGTH -gt 50 ]; then
          echo "::error::Invalid token length"
          exit 1
        fi

        echo "Token verified successfully"
