name: News Collector

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행
  workflow_dispatch:        # 수동 실행 가능

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notion-client requests python-dotenv

    - name: Check Token Format
      run: |
        TOKEN="${{ secrets.NOTION_TOKEN }}"
        if [[ ! $TOKEN == secret_* ]]; then
          echo "Error: NOTION_TOKEN must start with 'secret_'"
          exit 1
        fi
        echo "Token format verification passed"

    - name: Run collector
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python main.py
